[package]
name = "hoice"
version = "0.1.0"
authors = ["Adrien Champion <adrien.champion@email.com>"]

readme = "README.md"
categories = ["science"]
keywords = ["machine learning", "verification", "proof"]
license = "MIT"

[[bin]]
name = "hoice"
path = "src/bin/main.rs"
doc = false

[lib]
name = "hoice"
path = "src/hoice.rs"

[features]
bench = [ ]

[dependencies]
lazy_static = "*"
clap = "2.26.0"
regex = "*"
hashconsing = { git = "https://github.com/AdrienChampion/hashconsing" }
error-chain = "*"
log = "*"
env_logger = "*"
ansi_term = "*"
rsmt2 = { git = "https://github.com/kino-mc/rsmt2" }
num = "*"
mylib = { git = "https://github.com/AdrienChampion/mylib" }
rayon = "*"
